#!/usr/bin/env bash

# if no arguments passed - show help
if [[ $# -eq 0 ]];then
    lvcreate
    exit 3
fi

# save all arguments
all_args=$@
# volume group name is the last argument
vg_name=${@: -1}

# check if volume group contains a hyphen or space
echo "$vg_name" | grep "-" > /dev/null
if [[ $? -eq 0 ]]; then
    echo "Oops! This script can't work when Volume Group name contains a hyphen. Sorry."
    exit 1
fi

# find logical volume name
while [[ $# -gt 1 ]]; do
    key="$1"
    case $key in
        -n|--name)
        lv_name="$2"
        shift
        ;;
    esac
shift
done

# set mount point
mount_point="/$(echo $lv_name | tr "_" "/")"

set -e

echo "Create Logical Volume $lv_name in Volume Group $vg_name"
lvcreate $all_args

# find logical volume path (bash only)
lv_path=`lvdisplay ${vg_name}/${lv_name} | grep "LV Path"`
lv_path="${lv_path##* }"

echo "Formating Logical Volume $lv_name to ext4 format"
mkfs.ext4 "$lv_path"

# create directory if it doesn't exists
if [ ! -d "$mount_point" ]; then
    echo "Create directory $mount_point"
    mkdir -p "$mount_point"
fi

echo "Add record to /etc/fstab"
echo "$lv_path $mount_point ext4 defaults 0 0" >> /etc/fstab

echo "Mount $lv_name to $mount_point"
mount "$mount_point"
